### ISSUE TITLE
Orb style

### ISSUE THREAD

**Issue by christianwade** [RibbonWinForms/RibbonWinForms#11]
Evaluating to use in an existing app. I have a beautiful looking 2013 style ribbon

![image](https://user-images.githubusercontent.com/20731873/40523857-6ce4adb2-5f8c-11e8-8733-a3c5762df172.png)

But when I click the orb thing, it looks old style. How do I change to to look like 2013 style? (or at least get rid of the rounded border part)

![image](https://user-images.githubusercontent.com/20731873/40523929-b5b8109c-5f8c-11e8-872c-faa6969e638f.png)

**Comment by adriancs2** [comment]
Someone need to re-write this part.

**Comment by christianwade** [comment]
Thanks for the quick response. Short of someone rewriting this, I'm not sure of any way around it. The other ribbons I'm aware of are WPF based and I had issues hosting them in a Winforms app (in fact the author of that repo advised against it). If anyone is aware of any other workable solutions, please reply!

**Comment by allanjhonne** [comment]
Got any alternatives about the bug?

**Comment by tajbender** [comment]
I've found the rounded Border part is created using the "BorderRoundness" Properties.

@adriancs2: Do we want to fix this issue for Release 5, or will a fix in Release 6 be enough?

**Comment by tajbender** [comment]
I'll try to do my best, sir.

**Comment by adriancs2** [comment]
Thanks Taj :)

**Comment by tajbender** [comment]
That leads to a general question: How should the Orb DropDown-Menu look alike, as in Office 2013 e.g., there is none, instead these `RollOver`-things are used. (I'm currently not aware what the official name is, Application Menu?). I mean this part of the official Office Ribbon thing, that will consume the whole window frame when opened:

![Office 2013 - Application Menu](https://user-images.githubusercontent.com/10961499/63207309-bdfad980-c0c3-11e9-96a4-d07d5011e1b9.jpg)

The official Ribbon used in Windows whereas more looks like this, in Windows 10 e.g.:

![Orb Menu @ Windows Paint - Win10](https://user-images.githubusercontent.com/10961499/63207326-23e76100-c0c4-11e9-802c-578222bf81fd.jpg)

...and Windows 7 e.g.:

![AppMenu @ Windows Paint - Win7](https://user-images.githubusercontent.com/10961499/63207332-49746a80-c0c4-11e9-9177-ec316f88b9ad.png)

...which are pretty much the same, except for some colors and gradients.

To be honest, currently I can't see how much effort it would be integrate this into the current stable branch, but we won't get this done without cost, which leads to some efforts to merge into the other branch, finally.

As a compromise, for version 5, I suggest just getting rid of those rounded borders, when `BorderRoundness = 0` is set, and in version 6, we do the great punch for Office 2010 and '13-render paths...

@adriancs2 , @Baldemaier, @harborsiem: What are your thoughts about this?

**Comment by tajbender** [comment]
So, the easy fix would pretty much look like this:

![OrbStyle - Issue #11 - Easy Fix](https://user-images.githubusercontent.com/10961499/63207515-1a5ff800-c0c8-11e9-958a-4eaedcd13f64.png)

and be around ~10 lines of changes...

**Comment by adriancs2** [comment]
> As a compromise, for version 5, I suggest just getting rid of those rounded borders, when BorderRoundness = 0 is set, and in version 6, we do the great punch for Office 2010 and '13-render paths...
I'm ok with this.

**Comment by tajbender** [comment]
Fixed: [Fix Issue #11, "OrbStyle" - New and easy approach](https://github.com/RibbonWinForms/RibbonWinForms/pull/49)

**Comment by tarquinng-fletchint** [comment]
> That leads to a general question: How should the Orb DropDown-Menu look alike, as in Office 2013 e.g., there is none, instead these `RollOver`-things are used. (I'm currently not aware what the official name is, Application Menu?). I mean this part of the official Office Ribbon thing, that will consume the whole window frame when opened:


RollOver-things = **Backstage or Frontstage.** _...usually what you see is the backstage._ 

- The Frontstage is for when the app is open, but no documents are open. 

- The Backstage is for when a document is open.
