### ISSUE TITLE
MDI FORM doesn't move

### ISSUE THREAD

**Issue by Astronaar** [RibbonWinForms/RibbonWinForms#15]
I attemp to move an MDIForm while clicking on the top of the window and drag it.
The form doesn't move.
If you try with an simple form that doesn't inherit from Ribbonform, all is done normaly.
There also another problem with double click to restore fullcreen status of the form, it doesn't work too.
I try to search why, but some help will be appreciate.

Thx,

Astronäar

**Comment by adriancs2** [comment]
You show a form within a panel instead of MDI form

**Comment by Astronaar** [comment]
Hi adrian,
I finally found a solution, probably more a workaround.
I made some modifications in RibbonFormHelper.WndProc.

**Comment by adriancs2** [comment]
Hi, I have run a test with the latest version. This problem is gone.
You may try the nuget version.
Guide: How to add ribbon library via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki
