### ISSUE TITLE
Collapsible tabs

### ISSUE THREAD

**Issue by nfunwigabga** [RibbonWinForms/RibbonWinForms#22]
Is there any way to make the ribbon tabs collapsible?

**Comment by adriancs2** [comment]
I think it is not possible at the moment. You can look into the source code and see if you find any fixes.

**Comment by adriancs2** [comment]
Yes, the ribbon tabs are now can be collapsed. Following is an example:
```
ribbon1.Minimized = !ribbon1.Minimized;
```
