### ISSUE TITLE
Ribbon click events stop working when screen set to 125%

### ISSUE THREAD

**Issue by kebrite** [RibbonWinForms/RibbonWinForms#23]
As we want the top ribbon hidden after selecting something we add "Ribbon1.Minimized = true".   This way we maximize the amount of space on the screen.  What we have found is that when the screen resolution is set to 125% the click events for the ribbon no longer works to open any other screen????

Anyone know how to fix this?

Thanks
brendan

private void ribbonButton2_Click(object sender, EventArgs e)
        {
            foreach (Form f in MdiChildren)
            {
                if (f.GetType() == typeof(MDIChild1))
                {
                    f.Activate();
                    return;
                }
            }
            Form form = new MDIChild1
            {
                MdiParent = this
            };
            form.Show();
            **ribbon1.Minimized = true;**
        }

**Comment by adriancs2** [comment]
This problem has already fixed in new version.
You may try the Nuget version:
Guide: How to Add via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki

**Comment by kebrite** [comment]
Hi Adrian,



Thank you for letting me know it was updated.   I have added myself to the
GitHub notifications for new releases and I really appreciate the work that
you and the other contributors are doing!



Cheers,



*Brendan Keyhoe*

*Kebrite Solutions Inc.*

office: 604.210.2950 *x 200*

web: www.kebrite.com

links: support portal <https://kebriteportal.axosoft.com/login> &  file
upload <https://spaces.hightail.com/uplink/kebrite>

[image: e943ecc8-5be2-4768-a17e-1b829b908afe]
<https://www.facebook.com/Kebrite>[image:
541aa3ae-22f4-4ed9-bfd4-35cb8d8633b6]
<https://twitter.com/KebriteSolution>[image:
7b24d431-b33f-4266-8e00-6ec431907477]
<https://www.linkedin.com/company/kebrite-solutions-inc-?>

[image: 10Years]

CONFIDENTIALITY DISCLAIMER: The information contained in this transmission
may contain privileged and confidential information of Kebrite Solutions
Inc.   It is intended for review only by the person(s) named above.
Dissemination, distribution or duplication of this communication is
strictly prohibited by all recipients unless expressly authorized
otherwise.  If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message.
Kebrite® is a registered trademark of Kebrite Solutions Inc.



*From:* Adrian Voo <notifications@github.com>
*Sent:* Monday, August 19, 2019 8:24 AM
*To:* RibbonWinForms/RibbonWinForms <RibbonWinForms@noreply.github.com>
*Cc:* Kebrite Solutions Inc <bkeyhoe@kebrite.com>; Author <
author@noreply.github.com>
*Subject:* Re: [RibbonWinForms/RibbonWinForms] Ribbon click events stop
working when screen set to 125% (#23)



This problem has already fixed in new version.
You may try the Nuget version:
Guide: How to Add via Nuget:
https://github.com/RibbonWinForms/RibbonWinForms/wiki

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RibbonWinForms/RibbonWinForms/issues/23?email_source=notifications&email_token=ADLDJBYBNWUKQIGPNYADWGLQFK3KLA5CNFSM4GBQZAE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4TKOQI#issuecomment-522626881>,
or mute the thread
