### ISSUE TITLE
Using strings to manipulate Ribbon elements

### ISSUE THREAD

**Issue by WalterGuerraJr** [RibbonWinForms/RibbonWinForms#27]
Hi!

I would like to manipulate some properties of Ribbon elements (name, visible and enabled) dynamically with codes like these:

string Tb = "MyRibbonTab";
this.Controls [Tb] .Name = "Tab Save";

string Pnl = "MyRibbonPanel";
this.Controls [Pnl] .Name = "Pnl Save";

string Itm = "MyRibbonItem";
this.Controls [Itm] .Name = "Item Save As";

Anyone here can help me?

Thank you

**Comment by WalterGuerraJr** [comment]
Alternative solution and Is Good!!!

            rbbMenu.Tabs[2].Visible = false;
            rbbMenu.Tabs[0].Panels[1].Visible = false;
            rbbMenu.Tabs[1].Panels[0].Items[1].Visible = false;
            rbbMenu.Tabs[1].Panels[0].Items[0].Image = imgMenu.Images[18];

Thank You!!! ;)

**Comment by tajbender** [comment]
Thank you for contributing and posting your solution!
