### ISSUE TITLE
datagridview

### ISSUE THREAD

**Issue by hbwcv** [RibbonWinForms/RibbonWinForms#31]
hi
ribbon can support winform datagridview ?thanks!

**Comment by adriancs2** [comment]
yes

**Comment by hbwcv** [comment]
Can you give me some advice or demo?

**Comment by adriancs2** [comment]
Here is the sample:
[WindowsFormsApp1.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3071196/WindowsFormsApp1.zip)

**Comment by hbwcv** [comment]
Thank you very much!

but i actually want like that, thus navbar can be consistent with datagridview style:
![1](https://user-images.githubusercontent.com/46361903/56006871-28140400-5d09-11e9-8af2-df069600c33c.JPG)

**Comment by adriancs2** [comment]
The theme color of datagridview, you have to manually "color" it by changing the color properties of the datagridview.

**Comment by hbwcv** [comment]
OK,Thanks! I try it.
