### ISSUE TITLE
New development of Ribbon: Version 6

### ISSUE THREAD

**Issue by adriancs2** [RibbonWinForms/RibbonWinForms#40]
Dear developers,

tajbender (https://github.com/tajbender) has made a study on the code of current project where he has some findings as follow:

Back to the early stages, there were a few conditions to be considered, but as time went by and across several Windows Operating System, there were far too many things and conditions to be taken care and this resulting too many if else statements and hacking here and there, and this resulting a code base which is highly restricted it's potential to do further improvement. It is currently hardly maintainable.

It is suggested to do a brand new release. I personally agreed with tajbender.

I have restructured the repository and created a new folder called "Version 6". From here, a new code will start to evolve from here. As for this new repository, we will try to make it compatible across different platform, such as MONO, Net Core, Net Standard, etc.

@menendezpoo , @Baldemaier , @harborsiem , @KevboSlice , @tajbender , @jaydfox77 , @xsolon

**Comment by adriancs2** [comment]
@RibbonWinForms/RibbonWinForms

**Comment by tajbender** [comment]
I've created a GitHub-project for this brand new release:  [RibbonWinForms - Version 6](https://github.com/RibbonWinForms/RibbonWinForms/projects/1)

Please keep in mind that this Project is maintained by hobby enthusiasts in their spare free time. Contributions and ideas are always welcome, and every bit of help like suggesting features, posting bugs, adding assets like documentation or images etc. will be appreciated.

Thanks in advance!
