### ISSUE TITLE
Release or download available?

### ISSUE THREAD

**Issue by RussKie** [RibbonWinForms/RibbonWinForms#5]
There doesn't seem to be any public releases or Nuget packages available.
Is there a plan to provide some consumable binaries so we don't have to build the code ourselves?

**Comment by adriancs2** [comment]
Hi, I have compiled the ribbon and uploaded the binary to this repository. you can download the DLL at https://github.com/RibbonWinForms/RibbonWinForms/tree/master/Precompiled%20Binaries%20-%20Releases

**Comment by RussKie** [comment]
Awesome, thanks

**Comment by RussKie** [comment]
I guess, it is worth pointing that you could have just [created a release](https://github.com/RibbonWinForms/RibbonWinForms/releases) and uploaded binaries into it. This way you wouldn't need to commit them to the repo.

**Comment by adriancs2** [comment]
Hey dude, thanks ;)
