### ISSUE TITLE
System.ArgumentException: Version string portion was too short or too long.

### ISSUE THREAD

**Issue by yangpiena** [RibbonWinForms/RibbonWinForms#50]
![image](https://user-images.githubusercontent.com/19336724/65577726-f933d680-dfa6-11e9-8e50-eafb0ba8c86f.png)
Please help me，My system version is Windows XP,And my RibbonWinForms version is 5.0.1.1

**Comment by yangpiena** [comment]
And my RibbonWinForms version is 5.0.1.1

**Comment by adriancs2** [comment]
I have made a quick test on XP Service Pack 2 + .NET Framework 2.0 with the latest Nuget Release, it run ok at my side. Here is a sample project, you can have a look:
[XP_SP2_WinForms_Ribbon.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3653746/XP_SP2_WinForms_Ribbon.zip)

**Comment by yangpiena** [comment]
My running environment is XP Service Pack 3 + .NET Framework 4.0, I tried your sample can run ok.
But my project can't run ok with RibbonWinForms 5.0.1.1, and i'm back to version 5.0.0.0 is ok, why?

**Comment by yangpiena** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentException: 版本字符串部分太短或太长。
   在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   在 System.Version.TryParseVersion(String version, VersionResult& result)
   在 System.Version.Parse(String input)
   在 System.Version..ctor(String version)
   在 System.Windows.Forms.RibbonHelpers.WinApi.OSVersion.init()
   在 System.Windows.Forms.RibbonHelpers.WinApi.OSVersion.get_Version()
   在 System.Windows.Forms.RibbonHelpers.WinApi.get_IsWin10()
   在 System.Windows.Forms.RibbonFormHelper.SetMargins(Padding p)
   在 System.Windows.Forms.RibbonFormHelper.WndProc(Message& m)
   在 System.Windows.Forms.RibbonForm.WndProc(Message& m)
   在 xx.frm.FrmMain.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1022 (RTMGDR.030319-1000)
    基本代码: file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
xxOffline
    程序集版本: 1.0.0.19
    Win32 版本: 1.0.0.19
    基本代码: file:///C:/Program%20Files/Fimeson/xxOffline/xxOffline.exe
----------------------------------------
System
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1001 built by: RTMGDR
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1002 built by: RTMGDR
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1001 built by: RTMGDR
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms.Ribbon
    程序集版本: 2.0.0.0
    Win32 版本: 5.0.1.0
    基本代码: file:///C:/Program%20Files/Fimeson/xxOffline/System.Windows.Forms.Ribbon.DLL
----------------------------------------
System.Configuration
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1015 (RTMGDR.030319-1000)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1015 built by: RTMGDR
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 built by: RTMRel
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 built by: RTMRel
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ypn.common.csharp
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///C:/Program%20Files/Fimeson/xxOffline/ypn.common.csharp.DLL
----------------------------------------
System.Transactions
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
AutoUpdater.NET
    程序集版本: 1.5.7.0
    Win32 版本: 1.5.7.0
    基本代码: file:///C:/Program%20Files/Fimeson/xxOffline/AutoUpdater.NET.DLL
----------------------------------------
System.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 built by: RTMRel
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Web.Services
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
h13rurlz
    程序集版本: 1.0.0.19
    Win32 版本: 4.0.30319.1001 built by: RTMGDR
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 built by: RTMRel
    基本代码: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by yangpiena** [comment]
> I have made a quick test on XP Service Pack 2 + .NET Framework 2.0 with the latest Nuget Release, it run ok at my side. Here is a sample project, you can have a look:
> [XP_SP2_WinForms_Ribbon.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3653746/XP_SP2_WinForms_Ribbon.zip)

Please see my error.Thanks!

**Comment by adriancs2** [comment]
I have tried to run a simple test for XP SP3 + .NET 4.0 + Ribbon 5.0.1.1
The problem did not appear in my test.
You can check out the following sample project:
[WinFormsRibbon_Net4_XP_SP3.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3656869/WinFormsRibbon_Net4_XP_SP3.zip)

**Comment by yangpiena** [comment]
> I have tried to run a simple test for XP SP3 + .NET 4.0 + Ribbon 5.0.1.1
> The problem did not appear in my test.
> You can check out the following sample project:
> [WinFormsRibbon_Net4_XP_SP3.zip](https://github.com/RibbonWinForms/RibbonWinForms/files/3656869/WinFormsRibbon_Net4_XP_SP3.zip)

I have tried it many times and probably understand the cause of the error. It should be that the new project can run ok. Only the old project will be wrong if it is upgraded from version 5.0.0.0 to version 5.0.1.1 through NuGet. Now, I can only redesign the interface, if I continue to use version 5.0.1.1.
Thank you for your help！

**Comment by adriancs2** [comment]
Yes, I agree with you that redo the ribbon menu is the better choice. This is because in the process of fixing and improving the code, most of the time, backward compatibility is currently often not taken into consideration.

> Thank you for your help！

You're welcome.
