### ISSUE TITLE
Bug Excpetion PixelFormat is DontCare

### ISSUE THREAD

**Issue by vsc55** [RibbonWinForms/RibbonWinForms#6]
Fix Bug Excpetion PixelFormat is DontCare 
https://github.com/vsc55/RibbonWinForms/commit/eb9f3fca76ac87ab21204bc235420e21faf66d43

**Comment by RussKie** [comment]
Please replace tabs with space and sent a PR in

**Comment by vsc55** [comment]
It is already modified.
https://github.com/vsc55/RibbonWinForms/commit/be182964c790f7c63fb8d837b77ffaab87d9bff1

**Comment by vsc55** [comment]
It's been a pleasure.
That's what the community is for, help as much as possible.
