### ISSUE TITLE
Strange behavior with an app that manages parallel threads

### ISSUE THREAD

**Issue by gpsaliola** [RibbonWinForms/RibbonWinForms#68]
I've inserted the ribbon in an MDI form that manages other parallel threads (FileWatcher, GeoCoordinateWatcher, BackgroundWorker).
Everything works fine until a thread is started (example BackgroundWorker that do a sleep statement inside the doWork event).
The behavior of the ribbon is the following: events sometimes fires and sometimes not; some buttons remain highlighted as if the mouse was over them.
thanks for the tips.

**Comment by PandaWood** [comment]
It sounds like you're trying to access UI controls on a non-UI thread, which isn't supported by WinForms at all (this control or any other) ?
https://jonskeet.uk/csharp/threads/winforms.html

**Comment by gpsaliola** [comment]
Thank you for answer. 
I access the UI controls after testing with "invokequired" and using "invoke" method.
However I have given up on using this control.

**Comment by gpsaliola** [comment]
I solved it using Invoke statement
