### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by LaraSQP** [RibbonWinForms/RibbonWinForms#9]
Is there a Nuget package for this ribbon? If so, which? If not, are there plans to make one? I have never done one myself but would be willing to volunteer if you guys prefer.

Thanks for rebooting this project, btw.

**Comment by Padanian** [comment]
I will be happy to contribute too. I'm not a professional developer, but I've got a number of active apps on the store.
I only develop on winforms with Visual Studio 2017 and vb.net.

**Comment by RussKie** [comment]
> If not, are there plans to make one? I have never done one myself but would be willing to volunteer if you guys prefer.

It's fairly simple [to create a nuspec file](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package). 
you will have slightly bigger challenge in establishing a build pipeline that builds the solution, packs and publishes the nuget...

**Comment by LaraSQP** [comment]
I'm aware of the process and figure I could manage it, if it came to that. But my question was other.

**Comment by tajbender** [comment]
As far as I know, currently there is no NuGet-package available.

**Comment by adriancs2** [comment]
Hi, a nuget package has just released. You're welcome :)
https://www.nuget.org/packages/RibbonWinForm
